### PR TITLE
fix: use json handler from app

### PR DESCRIPTION
**Pull request by mammut53**
See comment below

### CODE REVIEW

**Comment by irgendwr** [comment]
Thanks for sumbitting a fix! It's really annoying how this company is acting.
You pull-request looks good, I will do some tests later and merge it afterwards.

You mention that it times out after 15min, we should either document that or handle it gracefully somehow.

**Comment by mammut53** [comment]
The 15 mins are only for the embedded handler, the url looks like this:
`https://www.dsbmobile.de/jhw-e13c6512-675a-4e52-a657-417f9fe7d461.ashx/GetData`

In my commit I'm using the handler which is used in the android app and which has no session based system in place:
`https://www.dsbmobile.de/JsonHandler.ashx/GetData`

What is maybe interesting to note is that they also took down `https://iphone.dsbcontrol.de/iPhoneService.svc/DSB/timetables/c195b49a-65a0-4bde-858c-9c4b37c67c7c` around the 17 Oct 19.

**Important**
Yesterday, everything worked fine with my version. Today, I noticed some sort of rate limit based on the appId which is used. It can be easily bypassed by just sending a random uuid.

**Review by irgendwr — CHANGES_REQUESTED** [review]
I ran the tests again and it doesn't work anymore, having a static appId is not a good idea.
We should check if the appId is generated randomly, follows a pattern or is acquired somehow.
I don't have time to look into this right now though.

**Review by mammut53 — COMMENTED** [review]
The appId is now randomly generated. Other parameters are now static based on some android phone.

**Review by irgendwr — APPROVED** [review]
Looks good as far as I can tell. :+1:
I will implement some way of setting the parameters after merging.

**Comment by irgendwr** [comment]
Thanks :)

**Pull request merged**
